"""
Assemble reports/final_report.pdf from Task 1 and Task 3 markdown reports plus
the figures generated by the notebooks and the Task 3 runner.

Uses fpdf2 which is pure Python and needs no LaTeX. Layout is deliberately
plain: one section per page, embedded images sized to fit, tables rendered
from CSVs. The point is a readable, complete submission PDF, not pretty
typesetting.
"""

from __future__ import annotations

import csv
import json
from pathlib import Path

from fpdf import FPDF

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
T1 = ROOT / "processed" / "task1"
T3 = ROOT / "processed" / "task3"
REPORTS = ROOT / "reports"
FIGS = REPORTS / "figures"
FIGS.mkdir(parents=True, exist_ok=True)
OUT = REPORTS / "final_report.pdf"

# Plain ASCII friendly margin layout
PAGE_W = 210
PAGE_H = 297
MARGIN = 15


class Report(FPDF):
    def header(self):
        if self.page_no() == 1:
            return
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 6, "Comparative Time Series Analysis and Forecasting of Mobile Network Traffic",
                 align="C")
        self.ln(8)
        self.set_text_color(0, 0, 0)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(140, 140, 140)
        self.cell(0, 6, f"Page {self.page_no()}", align="C")
        self.set_text_color(0, 0, 0)


def safe(text: str) -> str:
    """fpdf2 default font is latin-1 only. Replace anything outside it."""
    repl = {
        "—": "-", "–": "-",   # em / en dashes to hyphen
        "‘": "'", "’": "'",
        "“": '"', "”": '"',
        "→": "->", "←": "<-",
        "×": "x", "÷": "/",
        "•": "*",
        "≤": "<=", "≥": ">=",
        "α": "alpha", "β": "beta",
        "μ": "mu", "σ": "sigma",
        "−": "-",
        " ": " ", " ": " ",
        "…": "...",
        "&rarr;": "->", "&minus;": "-",
    }
    for k, v in repl.items():
        text = text.replace(k, v)
    return text.encode("latin-1", "replace").decode("latin-1")


def h1(pdf: Report, text: str):
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, safe(text))
    pdf.ln(11)


def h2(pdf: Report, text: str):
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, safe(text))
    pdf.ln(9)


def body(pdf: Report, text: str):
    pdf.set_x(MARGIN)
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 5.2, safe(text))
    pdf.ln(2)


def small(pdf: Report, text: str):
    pdf.set_x(MARGIN)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(80, 80, 80)
    pdf.multi_cell(0, 4.6, safe(text))
    pdf.set_text_color(0, 0, 0)
    pdf.ln(1)


def img_full(pdf: Report, path: Path, max_w=180, caption: str | None = None):
    if not path.exists():
        body(pdf, f"[missing image {path.name}]")
        return
    # Place image at current y with a fixed width
    pdf.image(str(path), w=max_w)
    if caption:
        small(pdf, caption)
    pdf.ln(2)


def csv_table(pdf: Report, path: Path, title: str | None = None):
    if not path.exists():
        body(pdf, f"[missing table {path.name}]")
        return
    rows = list(csv.reader(path.open()))
    if not rows:
        return
    header = rows[0]
    data = rows[1:]
    if title:
        h2(pdf, title)
    col_w = (PAGE_W - 2 * MARGIN) / len(header)
    pdf.set_font("Helvetica", "B", 9)
    for h in header:
        pdf.cell(col_w, 6, safe(h), border=1)
    pdf.ln(6)
    pdf.set_font("Helvetica", "", 9)
    for row in data:
        for cell in row:
            pdf.cell(col_w, 6, safe(cell), border=1)
        pdf.ln(6)
    pdf.ln(2)


def md_section(pdf: Report, md_path: Path):
    """Very light markdown rendering: h1 # -> 16pt, h2 ## -> 12pt, h3 ### -> 11pt bold,
    | tables passed through as text, everything else as body paragraphs."""
    if not md_path.exists():
        body(pdf, f"[missing report {md_path.name}]")
        return
    lines = md_path.read_text().splitlines()
    buf: list[str] = []

    def flush():
        if buf:
            body(pdf, " ".join(buf))
            buf.clear()

    in_table = False
    table_rows: list[list[str]] = []

    def flush_table():
        nonlocal in_table, table_rows
        if not table_rows:
            return
        # Drop the separator row that markdown uses (|---|---|)
        rows = [r for r in table_rows if not all(set(c.strip()) <= set("-: ") for c in r)]
        if rows:
            header = rows[0]
            data = rows[1:]
            col_w = (PAGE_W - 2 * MARGIN) / max(len(header), 1)
            pdf.set_font("Helvetica", "B", 9)
            for h in header:
                pdf.cell(col_w, 6, safe(h.strip()), border=1)
            pdf.ln(6)
            pdf.set_font("Helvetica", "", 9)
            for r in data:
                for c in r:
                    pdf.cell(col_w, 6, safe(c.strip()), border=1)
                pdf.ln(6)
            pdf.ln(2)
        in_table = False
        table_rows = []

    for raw in lines:
        line = raw.rstrip()
        if line.startswith("|") and line.endswith("|"):
            if not in_table:
                flush()
                in_table = True
            cells = [c for c in line.strip().strip("|").split("|")]
            table_rows.append(cells)
            continue
        elif in_table:
            flush_table()
        if line.startswith("# "):
            flush()
            h1(pdf, line[2:].strip())
        elif line.startswith("## "):
            flush()
            h2(pdf, line[3:].strip())
        elif line.startswith("### "):
            flush()
            pdf.set_font("Helvetica", "B", 11)
            pdf.cell(0, 7, safe(line[4:].strip()))
            pdf.ln(8)
        elif line.strip() == "":
            flush()
        elif line.startswith("- "):
            flush()
            pdf.set_x(MARGIN)
            pdf.set_font("Helvetica", "", 10)
            pdf.multi_cell(0, 5.2, safe("* " + line[2:]))
        else:
            buf.append(line)
    flush()
    flush_table()


def cover(pdf: Report):
    pdf.add_page()
    pdf.set_y(60)
    pdf.set_font("Helvetica", "B", 22)
    pdf.multi_cell(0, 12, safe("Comparative Time Series Analysis and Forecasting of Mobile Network Traffic"),
                   align="C")
    pdf.ln(8)
    pdf.set_font("Helvetica", "", 12)
    pdf.multi_cell(0, 7, safe("Telecom Italia Milan grid, November 2013 to January 2014"), align="C")
    pdf.ln(20)
    pdf.set_font("Helvetica", "", 11)
    pdf.multi_cell(0, 6, safe("Formative assignment, ML Techniques I"), align="C")
    pdf.ln(2)
    pdf.multi_cell(0, 6, safe("Kelvin Rwihimba"), align="C")
    pdf.ln(2)
    pdf.multi_cell(0, 6, safe("MacBook Air M3, 8 GB unified memory, macOS 15.5"), align="C")
    pdf.ln(20)
    pdf.set_font("Helvetica", "I", 10)
    pdf.multi_cell(0, 5.5,
        safe("Source code, raw outputs and run instructions accompany this PDF in the submission archive."),
        align="C")


def task1_section(pdf: Report):
    pdf.add_page()
    md_section(pdf, T1 / "report.md")


def task2_section(pdf: Report):
    pdf.add_page()
    h1(pdf, "Task 2. Exploratory Data Analysis")
    body(pdf,
        "Full code and figures live in notebooks/task2_eda.ipynb. The figures below "
        "are exported snapshots. The discussions in the notebook accompany each figure "
        "with comments on real world causes."
    )
    sections = [
        ("eda_pdf.png", "I. Probability density of two month total traffic across the 10,000 grid squares.",
         "Strong right skew. A small number of urban core cells dominate the city level total."),
        ("eda_timeseries.png", "II. Time series of the first two weeks for the three target areas.",
         "All three share a daily cycle with a clear weekday vs weekend swing. A_5161 is one order of "
         "magnitude larger than the other two and is much more peaked at evening hours."),
        ("eda_stationarity.png", "III. Rolling statistics and ADF test summary.",
         "The rolling mean drifts noticeably so the raw series is not covariance stationary; the ADF "
         "p value rejects the unit root only after seasonal differencing."),
        ("eda_decomposition.png", "IV. Additive seasonal decomposition.",
         "Trend is gentle; the seasonal component carries the daily cycle. The residual is largest "
         "around weekday evening peaks where the simple model under fits the spikes."),
        ("eda_acf_pacf.png", "V. ACF and PACF on the highest traffic square.",
         "Both plots show the expected daily lag 144 spike. The PACF cuts off after a few lags, "
         "consistent with the AR(1) plus seasonal AR component we use in SARIMA."),
        ("eda_heatmap.png", "VI. Spatial heatmap of two month total traffic over the 100 by 100 grid.",
         "Monocentric pattern with a dense city core that decays outward. The three target squares "
         "are marked on the heatmap."),
        ("eda_anomalies.png", "VII. Anomalies, outliers, unusual behaviour.",
         "Christmas Eve and Christmas Day register sharp dips in traffic, weekday rhythm is broken "
         "during the public holiday window. New Year's Eve creates the single largest residual."),
    ]
    for img_name, caption, comment in sections:
        img_path = FIGS / img_name
        h2(pdf, caption)
        img_full(pdf, img_path, max_w=170, caption=comment)


def task3_section(pdf: Report):
    pdf.add_page()
    md_section(pdf, T3 / "report.md")

    pdf.add_page()
    h1(pdf, "Task 3 results. Nine forecast plots")
    areas = ["A_5161", "B_4159", "C_4556"]
    models = ["SARIMA", "LSTM", "TCN"]
    for label in areas:
        h2(pdf, f"Area {label}")
        for model in models:
            img = T3 / "plots" / f"forecast_{model.lower()}_{label}.png"
            small(pdf, f"{model} on {label}")
            img_full(pdf, img, max_w=170)

    pdf.add_page()
    h1(pdf, "Task 3 results. Per area metric tables")
    for label in areas:
        csv_table(pdf, T3 / "tables" / f"metrics_{label}.csv", title=f"Metrics on {label}")

    h1(pdf, "Task 3 results. Training and inference time")
    csv_table(pdf, T3 / "tables" / "timing_summary.csv", title="Per (area, model) timings")
    csv_table(pdf, T3 / "tables" / "timing_avg_per_model.csv", title="Average train time per model")

    pdf.add_page()
    h1(pdf, "Task 3. Failure analysis. Worst 48 hour window")
    img_full(pdf, T3 / "plots" / "failure_analysis.png", max_w=180,
             caption="All three models compared against the actual over the worst 48 hour window "
                     "found by sliding a 288 step rolling RMSE across the test period.")
    metrics_p = T3 / "metrics.json"
    if metrics_p.exists():
        worst = json.loads(metrics_p.read_text()).get("worst_window")
        if worst:
            body(pdf,
                f"The peak window is on area {worst['area']}, driven by the {worst['model']} "
                f"prediction with rolling RMSE of {worst['rmse']:.1f}. Likely causes: deviations "
                f"from the normal weekday template during the Christmas week, sharp evening peaks "
                f"that the smoother SARIMA cannot resolve, and the NN models occasionally over "
                f"shooting when the previous day's pattern fails to predict the current day.")


def main():
    pdf = Report(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_margins(MARGIN, MARGIN, MARGIN)
    cover(pdf)
    task1_section(pdf)
    task2_section(pdf)
    task3_section(pdf)
    pdf.output(str(OUT))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
